name: RetroBar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    strategy:
      matrix:
        publishprofile: [ ReleaseProfile ]

    runs-on: windows-latest

    env:
      Solution_Name: RetroBar.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Publish app
      run: dotnet publish -p:PublishProfile=$env:Profile
      env:
        Profile: ${{ matrix.publishprofile }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: RetroBar
        path: RetroBar\bin\Release\netcoreapp3.1\publish\RetroBar.exe
