name: RetroBar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    strategy:
      matrix:
        publishprofile: [ x64, x86 ]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install nbgv
      uses: dotnet/nbgv@v0.4.0

    - name: Publish app
      run: dotnet publish -p:PublishProfile=$env:Profile -f netcoreapp3.1
      env:
        Profile: ${{ matrix.publishprofile }}

    - name: Copy license
      run: cp DistLicense.txt RetroBar\bin\Release\netcoreapp3.1\publish-${{ matrix.publishprofile }}\License.txt

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: RetroBar ${{ matrix.publishprofile == 'x86' && '32-bit' || '64-bit' }}
        path: |
          RetroBar\bin\Release\netcoreapp3.1\publish-${{ matrix.publishprofile }}\RetroBar.exe
          RetroBar\bin\Release\netcoreapp3.1\publish-${{ matrix.publishprofile }}\License.txt
