name: RetroBar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    strategy:
      matrix:
        publishprofile: [ AnyCPU ]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install nbgv
      uses: dotnet/nbgv@v0.4.0

    - name: Publish app
      run: dotnet publish -p:PublishProfile=$env:Profile -f net480
      env:
        Profile: ${{ matrix.publishprofile }}

    - name: Copy license
      run: cp DistLicense.txt RetroBar\bin\Release\net480\publish\License.txt

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: RetroBar
        path: RetroBar\bin\Release\net480\publish\
